//Default  URL
export const API_URL = 'http://localhost:5000/api';
export const USER_API_URL = 'http://192.168.29.64:6000/api';
export const AUTH_API_URL = 'http://192.168.29.64:4000/api';

//AUTH
export const LOGIN = 'LOGIN';
export const SET_LOGIN_DATA = 'SET_LOGIN_DATA';
export const SIGNUP = 'SIGNUP';
export const SET_SIGNUP_DATA = 'SET_SIGNUP_DATA';
export const FORGOTPASSWORD = 'FORGOTPASSWORD';
export const SET_FORGOTPASSWORD_DATA = 'SET_FORGOTPASSWORD_DATA';
export const LOGOUT = 'LOG_OUT';

//HOME

//DISHES
export const ADD_PRODUCT = 'ADD_PRODUCT';
export const SET_PRODUCT_DATA = 'SET_PRODUCT_DATA';
export const EDIT_PRODUCT = 'EDIT_PRODUCT';
export const SET_EDITED_PRODUCT_DATA = 'SET_EDITED_PRODUCT_DATA';
export const UPDATE_PRODUCT_STATUS = 'UPDATE_PRODUCT_STATUS';
export const SET_UPDATED_PRODUCT_STATUS = 'SET_UPDATED_PRODUCT_STATUS';
export const DELETE_PRODUCT = 'DELETE_PRODUCT';
export const SET_DELETED_PRODUCT_DATA = 'SET_DELETED_PRODUCT_DATA';
export const GET_PRODUCTS = 'GET_PRODUCTS';
export const SET_RECIEVED_PRODUCTS_DATA = 'SET_RECIEVED_PRODUCTS_DATA';

// RESTAURANTS

export const ADD_RESTAURANTS = 'ADD_RESTAURANTS';
export const SET_RESTAURANTS_DATA = 'SET_RESTAURANTS_DATA';
export const SET_RESTAURANT_DATA = 'SET_RESTAURANT_DATA';
export const EDIT_RESTAURANT = 'EDIT_RESTAURANT';
export const SET_EDITED_RESTAURANT_DATA = 'SET_EDITED_RESTAURANT_DATA';
export const UPDATE_RESTAURANT_STATUS = 'UPDATE_RESTAURANT_STATUS';
export const SET_UPDATED_RESTAURANT_STATUS = 'SET_UPDATED_RESTAURANT_STATUS';
export const GET_RESTAURANT = 'GET_RESTAURANT';
export const SET_RECIEVED_RESTAURANT_DATA = 'SET_RECIEVED_RESTAURANT_DATA';
export const GET_ALL_RESTAURANT = 'GET_ALL_RESTAURANT';
export const SET_RECIEVED_ALL_RESTAURANT_DATA =
  'SET_RECIEVED_ALL_RESTAURANT_DATA';

//Profile
export const PROFILE = 'PROFILE';
export const SET_PROFILE_DATA = 'SET_PROFILE_DATA';
